a = 15
b = 4
# Addition (+)
print("Addition:",a+b)
# Subtraction (-)
print("Subtraction:",a-b)
# Multiplication (*)
print("Multiplication:",a*b)
# True Division - Float result (/)
print("Division:",a/b)
# Floor Division - Quotient (//)
print("Floor Division:",a//b)
# Modulus - Remainder (%)
print("Modulus:",a%b)
# Exponential - Power (**)
print("Exponential:",a**b)