import numpy as np
scores_array = np.array([10,20,30,40,50])
print(scores_array)
print(scores_array[0])
print(scores_array[2])
print(scores_array[-1])
print(scores_array[-2])
# 2-D array
marks_matrix = np.array([[90,85,80],[70,75,65]])
print(marks_matrix)
# Row index and column index
print(marks_matrix[0,0])
print(marks_matrix[0,1])
print(marks_matrix[0,2])
print(marks_matrix[1,0])
print(marks_matrix[1,1])
print(marks_matrix[1,2])
print(marks_matrix[0])
# 3-D array
cube_data_array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(cube_data_array)
print(cube_data_array[0,0,0])
print(cube_data_array[0,1,2])
print(cube_data_array[1,0,1])
print(cube_data_array[1,1,2])